# Generated by Django 5.2.5 on 2025-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
