# Generated by Django 5.2.5 on 2025-08-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCompany', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
