# Generated by Django 5.2.5 on 2025-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCompany', '0004_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
